name: theme_best_practice
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.8.0-dev <3.0.0"
  flutter: ">=1.14.6 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  enum_to_string:
  fl_chart:
  mono_kit:
  nested:
  provider:
  recase:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
dependency_overrides:
  provider:
    git:
      url: https://github.com/rrousselGit/provider.git
      ref: extensions
  mono_kit:
    path: ../flutter_mono_kit
flutter:
  uses-material-design: true
