name: theme_best_practice
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.8.0-dev <3.0.0"
  flutter: ">=1.14.6 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  mono_kit: ^0.12.4+1
  pedantic_mono:
  provider:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
